# Generated by Django 4.0 on 2021-12-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
    ]
